Pop-up modal
zemola/MY-PORTFOLIO pull request #13
Opened 2021-11-10 21:03 UTC by zemola

# MY PORTFOLIO POP-UP MODAL 

Collaborated with my coding partner in developing a pop-up modal for my portfolio putting in mind the following criteria.

1. On desktop, when the user clicks on the "Next project" / "Previous project" buttons, they will navigate to the next/previous project details in the popup.
2. If the project is the first one, the "Previous project" button is disabled
3. If the project is the last one, the "Next project" button is disabled

![image](https://user-images.githubusercontent.com/59098116/141192528-602aa6ab-0fd8-4787-ba8f-e169e93f3555.png)

2021-11-10 23:52 UTC, rotimiazeez requested changes
# Hi @zemola 👋, 

### Good job so far!💯

### To highlight 👏
- Good UI 👌
- Good README 👍
- Descriptive PR message 😉
- No Linter error ✔
#### There are some issues that you still need to work on to go to the next project but you are almost there!
#### Just a few steps and you are unstoppable😎

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 23:52 UTC, rotimiazeez commented on index.html
> +          </div>
- [ ] Please make sure the popup follows the design for both desktop and mobile version from the chosen template in Figma (e.g., font, colours, images, tests, margins).
- Your design
![screenshot (2)](https://user-images.githubusercontent.com/44624138/141211621-dd766b10-0a7d-4317-a4d8-9d2e3f4cbe56.png)
- Figma design
![screenshot (3)](https://user-images.githubusercontent.com/44624138/141211638-49fb2cce-9075-413b-8864-ad1099e430fb.png)

2021-11-10 23:52 UTC, rotimiazeez commented on index.html
> +                </a>
Please make sure this also match your preferred template design✔👌
- Your Design
![screenshot (4)](https://user-images.githubusercontent.com/44624138/141211854-54c050cd-2532-4732-a7d2-de57843953d8.png)
- Figma Design
![screenshot (5)](https://user-images.githubusercontent.com/44624138/141211864-18426599-ef92-45e8-b7cd-f5492bf1ae71.png)

2021-11-11 12:11 UTC, bimbolabuari approved these changes
# Project Approved 🚀

Hi @zemola 🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-11 13:52 UTC, merged